// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArYDkYX-LjuGSF_o13bHjCqyfL6USrN3s',
    appId: '1:901636572965:web:8dc01c94502bd5cb7dfccc',
    messagingSenderId: '901636572965',
    projectId: 'ecomm-6e687',
    authDomain: 'ecomm-6e687.firebaseapp.com',
    storageBucket: 'ecomm-6e687.firebasestorage.app',
    measurementId: 'G-Z48GD90E9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWJ9Xd4-3Bai4JnpfLdZmhaviODVU6nZQ',
    appId: '1:901636572965:android:e6ac2eccdda0c68f7dfccc',
    messagingSenderId: '901636572965',
    projectId: 'ecomm-6e687',
    storageBucket: 'ecomm-6e687.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAwILiX-cGCImWXuPs5FbivANf7qzEBTI',
    appId: '1:901636572965:ios:1ed1e51ab45ba48a7dfccc',
    messagingSenderId: '901636572965',
    projectId: 'ecomm-6e687',
    storageBucket: 'ecomm-6e687.firebasestorage.app',
    iosBundleId: 'com.example.eCom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAwILiX-cGCImWXuPs5FbivANf7qzEBTI',
    appId: '1:901636572965:ios:1ed1e51ab45ba48a7dfccc',
    messagingSenderId: '901636572965',
    projectId: 'ecomm-6e687',
    storageBucket: 'ecomm-6e687.firebasestorage.app',
    iosBundleId: 'com.example.eCom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArYDkYX-LjuGSF_o13bHjCqyfL6USrN3s',
    appId: '1:901636572965:web:7fc862d6c19a8fb87dfccc',
    messagingSenderId: '901636572965',
    projectId: 'ecomm-6e687',
    authDomain: 'ecomm-6e687.firebaseapp.com',
    storageBucket: 'ecomm-6e687.firebasestorage.app',
    measurementId: 'G-TBYKD31FBM',
  );

}